// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD66JZZh_9kJBsqnNflxINZO_bVz1IRoXs',
    appId: '1:1002228149306:web:a9add9c8f8233ff1cf1903',
    messagingSenderId: '1002228149306',
    projectId: 'harinatodoproposito',
    authDomain: 'harinatodoproposito.firebaseapp.com',
    databaseURL: 'https://harinatodoproposito-default-rtdb.firebaseio.com',
    storageBucket: 'harinatodoproposito.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkgYZXq0rGpTejpJ3sxqWP2OxQ3n5l_Cc',
    appId: '1:1002228149306:android:cee87507fca4c17ecf1903',
    messagingSenderId: '1002228149306',
    projectId: 'harinatodoproposito',
    databaseURL: 'https://harinatodoproposito-default-rtdb.firebaseio.com',
    storageBucket: 'harinatodoproposito.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk5bDoujrfMfk9Dwma2IXBqr_HYvo5dzg',
    appId: '1:1002228149306:web:488d721e7c95eb3bcf1903',
    messagingSenderId: '1002228149306',
    projectId: 'harinatodoproposito',
    authDomain: 'harinatodoproposito.firebaseapp.com',
    databaseURL: 'https://harinatodoproposito-default-rtdb.firebaseio.com',
    storageBucket: 'harinatodoproposito.firebasestorage.app',
  );
}
